import React, { useMemo, useState } from "react";
import ReactDOM from "react-dom/client";
import { createClient } from "genlayer-js";
import { studionet } from "genlayer-js/chains";
import { TransactionStatus, type Hash } from "genlayer-js/types";
import "./styles.css";

declare global { interface Window { ethereum?: { request: (x:{method:string}) => Promise<string[]> } } }
type Bundle = {bundle_id:string;submitter:string;assessor:string;repository:string;commit:string;tag:string;policy:string;manifest_sha256:string;fingerprint:string;status:string;outcome:string;results:string[];attestation_id:string};
const EXPLORER="https://explorer-studio.genlayer.com";
const POLICY="RELEASE_DISCLOSURE_V1";
const DEPLOYED_CONTRACT=import.meta.env.VITE_CONTRACT_ADDRESS||"0x69310D0B876F47007eafFCB57B3a8DB0c884E3a5";

function App(){
  const [account,setAccount]=useState(""),[contract,setContract]=useState(localStorage.getItem("releaseproof.contract")||DEPLOYED_CONTRACT);
  const [bundleId,setBundleId]=useState("0"),[bundle,setBundle]=useState<Bundle|null>(null),[busy,setBusy]=useState(""),[message,setMessage]=useState("Ready for a verified StudioNet deployment.");
  const [owner,setOwner]=useState("owner"),[repository,setRepository]=useState("repository"),[commit,setCommit]=useState(""),[tag,setTag]=useState("v1.0.0"),[manifest,setManifest]=useState('[{"path":"LICENSE","sha256":"","bytes":0},{"path":"SECURITY.md","sha256":"","bytes":0},{"path":"README.md","sha256":"","bytes":0}]'),[manifestHash,setManifestHash]=useState("");
  const [journal,setJournal]=useState<{label:string;hash:string}[]>([]);
  const readClient=useMemo(()=>createClient({chain:studionet}),[]);
  const valid=/^0x[0-9a-fA-F]{40}$/.test(contract);
  async function connect(){if(!window.ethereum){setMessage("No injected wallet found.");return}try{const accounts=await window.ethereum.request({method:"eth_requestAccounts"});if(!accounts[0])throw new Error("No account selected");const client=createClient({chain:studionet,provider:window.ethereum,account:accounts[0] as `0x${string}`});await client.connect("studionet");setAccount(accounts[0]);setMessage("Wallet connected to StudioNet.")}catch(e){setMessage(e instanceof Error?e.message:"Wallet connection cancelled")}}
  function saveContract(value:string){const clean=value.trim();setContract(clean);localStorage.setItem("releaseproof.contract",clean);setBundle(null)}
  async function loadBundle(id:string){const raw=await readClient.readContract({address:contract as `0x${string}`,functionName:"get_bundle",args:[id]});if(raw==="NOT_FOUND")throw new Error("Bundle not found");const parsed=JSON.parse(String(raw)) as Bundle;setBundle(parsed);return parsed}
  async function read(id=bundleId){if(!valid){setMessage("Paste the deployed contract address first.");return}setBusy("read");try{await loadBundle(id);setMessage("Authoritative contract state loaded.")}catch(e){setMessage(e instanceof Error?e.message:"Read failed")}finally{setBusy("")}}
  async function write(label:string,method:string,args:string[]){if(!valid||!account||!window.ethereum){setMessage("Set the contract and connect a wallet first.");return}setBusy(method);try{const version=JSON.parse(String(await readClient.readContract({address:contract as `0x${string}`,functionName:"get_contract_version",args:[]})));if(version.name!=="ReleaseProof"||version.version!==1||version.schema!=="content-addressed-disclosure-v1")throw new Error("Contract schema mismatch. Refusing to write.");let target=bundleId;let before=-1;if(method==="register_bundle"){before=Number(JSON.parse(String(await readClient.readContract({address:contract as `0x${string}`,functionName:"get_counts",args:[]}))).bundles);target=String(before)}const client=createClient({chain:studionet,provider:window.ethereum,account:account as `0x${string}`});await client.connect("studionet");const hash=String(await client.writeContract({address:contract as `0x${string}`,functionName:method,args,value:0n}));setJournal(items=>[{label,hash},...items]);setMessage("Signed. Waiting for finality and authoritative readback…");await readClient.waitForTransactionReceipt({hash:hash as Hash,status:TransactionStatus.FINALIZED,interval:5000,retries:240});if(method==="register_bundle"){const after=Number(JSON.parse(String(await readClient.readContract({address:contract as `0x${string}`,functionName:"get_counts",args:[]}))).bundles);if(after!==before+1)throw new Error("Finalized, but bundle count did not advance. The contract rejected registration.");setBundleId(target)}const post=await loadBundle(target);if(method==="assess_bundle"&&post.status!=="ATTESTED")throw new Error(`Finalized, but authoritative state is ${post.status}; assessment was not accepted.`);setMessage(`${label} finalized and authoritative state matched.`)}catch(e){setMessage(e instanceof Error?e.message:`${label} failed`)}finally{setBusy("")}}
  const commitValid=/^[0-9a-fA-F]{40}$/.test(commit);
  const manifestHashValid=/^[0-9a-fA-F]{64}$/.test(manifestHash);
  const registerReady=valid&&Boolean(account)&&Boolean(owner.trim())&&Boolean(repository.trim())&&commitValid&&manifestHashValid&&!busy;
  const assessReady=valid&&Boolean(account)&&/^\d+$/.test(bundleId)&&!busy;
  const registerHint=!account?"Connect the submitter wallet to continue.":!commitValid?"Enter the full 40-character commit SHA.":!manifestHashValid?"Enter the 64-character manifest SHA-256.":!owner.trim()||!repository.trim()?"GitHub owner and repository are required.":"Ready to register. Your wallet will request a signature.";
  const assessHint=!account?"Connect the independent auditor wallet to continue.":!/^\d+$/.test(bundleId)?"Enter a numeric bundle ID.":"Ready to assess. Your wallet will request a signature.";
  return <div className="app">
    <header><a className="brand" href="#top"><img src="/releaseproof-logo.png"/><span><b>ReleaseProof</b><small>Immutable disclosure attestation</small></span></a><div className="network"><i/>StudioNet</div><button className="wallet" onClick={connect}>{account?`${account.slice(0,6)}…${account.slice(-4)}`:"Connect wallet"}</button></header>
    <main id="top">
      <section className="intro"><div><p className="kicker">SOURCE-PINNED · INDEPENDENTLY ASSESSED</p><h1>Verify what a release <em>actually discloses.</em></h1><p className="lede">Bind three release documents to one immutable Git commit. GenLayer verifies the bytes, then an independent wallet assesses disclosure presence—without claiming the documents are true.</p></div><aside><span>POLICY 01</span><b>Release Disclosure</b><p>LICENSE · SECURITY.md · README.md</p><strong>No mutable branches.<br/>No arbitrary source URLs.</strong></aside></section>
      <section className="how"><div><p className="kicker">HOW IT WORKS</p><h2>One release. Two roles. Three verified files.</h2></div><ol><li><span>01</span><div><b>Pin the source</b><p>The submitter registers a full Git commit and a canonical manifest for LICENSE, SECURITY.md and README.md.</p></div></li><li><span>02</span><div><b>Verify independently</b><p>A separate auditor wallet asks GenLayer validators to fetch the commit-pinned files and verify their exact bytes.</p></div></li><li><span>03</span><div><b>Publish the attestation</b><p>The contract records the bounded disclosure result and exposes authoritative state for anyone to read.</p></div></li></ol></section>
      <section className="contract-strip"><label><span>Deployed contract</span><input value={contract} onChange={e=>saveContract(e.target.value)} placeholder="0x… deploy with the primary wallet"/></label><button onClick={()=>read()} disabled={!valid||Boolean(busy)}>Read bundle</button></section>
      <section className="workflow">
        <div className="form-card"><div className="number">01</div><div><p className="kicker">SUBMITTER WALLET</p><h2>Register immutable bundle</h2></div><div className="fields"><label>GitHub owner<input value={owner} onChange={e=>setOwner(e.target.value)}/></label><label>Repository<input value={repository} onChange={e=>setRepository(e.target.value)}/></label><label className="wide">40-character commit SHA<input value={commit} onChange={e=>setCommit(e.target.value)} placeholder="Full commit, never main or latest"/></label><label>Release tag<input value={tag} onChange={e=>setTag(e.target.value)}/></label><label>Policy<input value={POLICY} readOnly/></label><label className="wide">Canonical manifest JSON<textarea value={manifest} onChange={e=>setManifest(e.target.value)}/></label><label className="wide">Manifest SHA-256<input value={manifestHash} onChange={e=>setManifestHash(e.target.value)}/></label></div><div className="action"><button className="primary" disabled={!registerReady} onClick={()=>write("Register bundle","register_bundle",[owner,repository,commit,tag,POLICY,manifest,manifestHash])}>{busy==="register_bundle"?"Waiting for finality…":"Register content-addressed bundle"}</button><p className={registerReady?"ready":"requirement"}>{registerHint}</p></div></div>
        <div className="assess-card"><div className="number">02</div><div><p className="kicker">INDEPENDENT AUDITOR WALLET</p><h2>Assess & attest</h2></div><label>Bundle ID<input value={bundleId} onChange={e=>setBundleId(e.target.value)}/></label><p>The submitter and deployer are rejected here. Switch to the independent auditor wallet before assessing.</p><div className="action"><button className="primary orange" disabled={!assessReady} onClick={()=>write("Assess bundle","assess_bundle",[bundleId])}>{busy==="assess_bundle"?"Validators are assessing…":"Run independent assessment"}</button><p className={assessReady?"ready":"requirement"}>{assessHint}</p></div></div>
      </section>
      <section className="report"><div className="report-head"><div><p className="kicker">PUBLIC ATTESTATION</p><h2>{bundle?.repository||"No bundle loaded"}</h2><p>{bundle?`${bundle.tag} · ${bundle.commit.slice(0,12)}…`:"Enter a bundle ID and read authoritative state."}</p></div><span className={`badge ${bundle?.status==="ATTESTED"?"done":""}`}>{bundle?.outcome||"AWAITING EVIDENCE"}</span></div><div className="checks">{["LICENSE","SECURITY.md","README.md"].map((name,index)=><div key={name}><span>{String(index+1).padStart(2,"0")}</span><b>{name}</b><strong>{bundle?.results[index]||"NOT ASSESSED"}</strong></div>)}</div>{bundle?.attestation_id&&<div className="attestation"><span>Attestation ID</span><code>{bundle.attestation_id}</code></div>}</section>
      <section className="status-line"><b>System status</b><p>{message}</p></section>
      <section className="journal"><div><p className="kicker">TRANSACTION PROOF</p><h2>Finalized writes</h2></div>{journal.length?<div>{journal.map(item=><a key={item.hash} href={`${EXPLORER}/tx/${item.hash}`} target="_blank"><b>{item.label}</b><code>{item.hash.slice(0,12)}…{item.hash.slice(-8)}</code><span>Open Explorer ↗</span></a>)}</div>:<p>No writes signed in this browser session.</p>}</section>
    </main>
    <footer><b>ReleaseProof</b><p>Disclosure presence is not legal compliance, security assurance, provenance truth, or endorsement.</p>{valid&&<a href={`${EXPLORER}/address/${contract}`} target="_blank">Contract on Explorer ↗</a>}</footer>
  </div>
}

ReactDOM.createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);
